version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: crypto-js
    versions:
    - "> 3.1.9-1"
  - dependency-name: eslint
    versions:
    - 7.20.0

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
