language: node_js
node_js:
- node
- '10'
- '8'

# https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing
matrix:
  fast_finish: true

script: npm test -- --coverage --verbose

after_success:
  - |
    $(npm bin)/set-up-ssh \
      --key "$encrypted_1001587ab084_key" \
      --iv "$encrypted_1001587ab084_iv" \
      --path-encrypted-key ".travis/github_deploy_key.enc"

    # Only commit build artifacts on one node to avoid git errors
    if [ "$TRAVIS_NODE_VERSION" == "node" ]
    then
      # Build w/o the testing flag set so testing code will be removed
      npm run build

      # Force add files in ./dist, despite the .gitignore
      git add --force ./dist

      # --commands is unecessary but required, so it's effectively a no-op
      # --branch makes sure this only happens on master
      $(npm bin)/commit-changes \
        --commands "echo committing changes" \
        --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" \
        --branch "master"
    fi

env:
  global:
    - secure: "JdYaM+SoHMay0sR5aqTzAt7BM7W/v8HbuXm14nEfUbXMhkDQi44qyAJCh35qLw/Zb8cWgOSQsMUQXoyLSsfTNDbml6UrVJC6t6EQ2bGLx+Wj6+PNyE1qm/BZDI9TIWD8oZ+95jNVfpjFzmLUTqMmFm    4fdXnDV76orGYfMN2IPBOoK3Lh2jicSh5Cxy0DvL8Y4QxsySO8kGyzKGetFZnrsvg3eABDSjI5Hp99DUmMpbD8LyEx68mYwnFpBo6Xf36AoTvpk5FDYXVmM1a5LTlluOKYv5ccBgBkvhA+W3uwNQ4ENWuP2dWkmdB4LyEfBRad7jDUXx8doI8jJYHURRKUZRNF5gFHhYVwbe3oJy4ggBoN9W+zTENtb6811JDv5gaqEayBPoO74N67pZxhPomWPWA77d5Zy0g8vsIeJd8TqRgiaQ0+BVG4X1pNzQwu5EKkekZAerU1yG/jTSzfB6T7vN2P2ND2MOmRteYezsH1aJjePCsjH/+Rmb8xTgwEMGHNfQawBqUtPg3mONnC3qxTmmRbK+7DadNplI92CtLJ7pRJV2lrkBnzN2we0gt2Vh/Ydo62WCrrJ/5eTZnsHcy61W5CUNIvbTzndCmzsZPR5K9+OAfW5YzYhYQAOhJgZtFkESGYWz9WWYLKcy0l2YTw2VVdLa3GsYlrmyWpy+oefFY="

deploy:
  - provider: npm
    email: npm@patcavit.com
    skip_cleanup: true
    api_key:
      secure: KLrn47T9isS/c36lCbx0eFMTd3PGmRLJPh1H8t4aGerP0xJuIYt34t8DHhJSJwv1soigjAZZqg1bjLEzjtzZ79kYjIPPzIvdIhSath559i+HiuIOPDEzXivBgadlxaRM8WPKj8VevbhPAsJ7hOWJ0OzP0OzFmhz45KPq6JVBWKipShil2W7DQUR/g7z0p3KHMGdccj28zjyO0p3q7vshHCDzFsSeRRTwFjHwWYwHwZW/pDnfVBzOJZg7Foi9tet28hVQFY7qx2HkaQ+UgwDpQWfUb7GVulIPymgktnhcfAQzAEGVg+k/441ZULhHu7T1peiUySLmNJwdj/AnIm1Ur/fqyq8JfgncptqO2rS5DVRcq+SiZA5CVbs8veEiXGLihpzsEwocZWCfGcUac9ScdIIToH1E9g7ADTJEl5L+uSduBTiY0aMKMdcIOP+FZqqdpHi/yVU5E2A2hJgf0FcHurNzKF0e0ye7OFUY4inYrhAPe79zRHet2Z+0xsGqgLL84q04qKGmgrWt0QxuyrIjehErSAzoMhVnuLEzYKLfYSA+FeVGG47oBcg93lxtlWpeu/u+jBpTb1X31S3T/GXBlos6wYwwbf4evbuE2OtAmIt/zg6d/C/SfGJz41xv/AkHellzhceFmJxdXU0xcCTuOpoce1F33GaZdg0VhA8MngQ=
    on:
      tags: true
      repo: tivac/aws-sig
      node: node
