name: Tests

on: [ push ]

jobs:
  test:
    name: node@${{ matrix.node_version }} on ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node_version: [ 10, 12 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: npm install
      run: npm install
    
    - name: Run Tests
      run: npm test -- --ci --verbose

    # Run codecov after all builds, and only on a single environment
    - name: Code Coverage
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '12'
      run: |
        npm test -- --ci --coverage
        npx codecov
