name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

  test:
    name: node@${{ matrix.node_version }} on ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node_version: [ 12, 14, 16 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install node@${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test
      run: npm test -- --ci --verbose

    # Run codecov after all builds, and only on a single environment
    - name: Gather Coverage
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '14'
      run: npm test -- --ci --coverage
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '14'
      with:
        files: ./coverage/coverage-final.json


